version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
    commit-message:
      prefix: Change
