version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Tokyo
    pull-request-branch-name:
      separator: "-"
    target-branch: "maintain"
    open-pull-requests-limit: 1
    versioning-strategy: increase
