pull_request_rules:
  - name: auto_merge
    conditions:
      - base=maintain
    actions:
      merge:
        strict: smart
  - name: auto_update
    conditions:
      - base=main
    actions:
      update: {}
