pull_request_rules:
  - name: auto_merge
    conditions:
      - base=main
      - author=dependabot[bot]
      - label=dependencies
      - files=package.json
      - check-success=cpuabuse.eslint-config.test
      - check-success=Codacy Static Code Analysis
    actions:
      review:
        type: APPROVE
      merge:
        method: merge
