pull_request_rules:
  - name: auto_review_dependabot
    conditions:
      - base=main
      - author=dependabot[bot]
    actions:
      review: {}
  - name: auto_merge_pull_request
    conditions:
      - base=main
    actions:
      merge:
        strict: smart
