pull_request_rules:
  - name: auto_merge
    conditions:
      - base=main
      - author=dependabot[bot]
      - check-success=cpuabuse.eslint-config.test
      - check-success=Codacy Static Code Analysis
    actions:
      review:
        bot_account: badelgatobot
      merge:
        strict: smart
