pull_request_rules:
  - name: auto_merge
    conditions:
      - author=dependabot
      - label=dependencies
      - "#conflict"
      - files=package.json
      - check-success=cpuabuse.eslint-config.test
      - check-success=Codacy Static Code Analysis
    actions:
      merge:
        method: merge
