# Include parentheses around a sole arrow function parameter
# Minimal syntax
arrowParens: avoid

# Specify the line length that the printer will wrap on
# Adapt to bigger screens
printWidth: 120

# Print trailing commas wherever possible when multi-line
# Make no sense
trailingComma: none

# Indent lines with tabs instead of spaces
# It is personal preference of developer to set tab width in IDE
useTabs: true

# HTML Whitespace Sensitivity
# There are times when this might be necessary
htmlWhitespaceSensitivity: strict

# Specify the line length that the printer will wrap on
# Preserve yaml for actions and azure pipelines; keep single quotes
overrides:
  - files:
      - "pipeline/**/*.azure-pipelines.yml"
      - ".github/workflows/**/*.yml"
    options:
      printWidth: 960
      singleQuote: true
