on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: merge
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(await github.checks.listForRef({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}",
              ref: "${{ github.ref }}",
            }))
