on: push

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: create
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "chore(maintain): automated maintenance",
              head: "maintain",
              base: "main",
              body: "# Description\n\nAutomated maintenance.",
              maintainer_can_modify: true
            });
